# Configuration file for NLP pipeline

steps:
  actions:
    - type: data_cleaning
      is_execute: false
      file_input: "app/data/raw/tripadvisor_original.csv"
      file_output: "app/data/cleaned/tripadvisor_sentence_cleaned.csv"
      split_mode: "token"
      custom_stopwords: ["th", "nt", "got", "like", "just", "thing", "went", "come", "back", "make", "one", "would", "could", "also", "time", "day", "night", "hotel", "stay", "stayed", "place"]

    - type: eda
      is_execute: false
      file_input: "app/data/cleaned/tripadvisor_sentence_cleaned.csv"

    - type: topic_modeling
      is_execute: false
      file_input: "app/data/cleaned/tripadvisor_sentence_cleaned.csv"
      file_output: "app/data/topics/lda_topics.csv"
      num_topics: 5

    - type: topic_labeling
      is_execute: false
      file_input: "app/data/topics/lda_topics_topics.csv"
      file_output: "app/data/topics/lda_topics_labeled.csv"
      candidate_labels: ["Room", "Staff", "Booking Issues", "Beach And Resort","Tourist Attractions", "Cleanliness", "Customer Support", "Food And Dining", "Transportation", "Location"]

    - type: sentence_sentiment_analysis
      is_execute: true
      method: "bert" # Options: "vader", "textblob", "bert"
      file_input: "app/data/topics/lda_topics.csv"
      file_output: "app/data/topics/lda_topics_sentiment.csv"

    # - type: analyze_sentiment_topic_modeling
    #   is_execute: false
    #   file_input: "app/data/topics/lda_topics.csv"
    #   file_output: "app/data/topics/topic_sentiment_distribution.csv"
    #   vectorizer_input: "app/data/features/tfidf_vectorizer.pkl"
    #   model_input: "app/data/train_models/tfidf_logistic_regression_sentiment_model.pkl"