# Configuration file for NLP pipeline

steps:
  actions:
    - type: data_cleaning
      is_execute: false
      file_input: "app/data/raw/tripadvisor.csv"
      file_output: "app/data/cleaned/tripadvisor_sentence_cleaned.csv"
      split_mode: "sentence"

    - type: sentence_sentiment_analysis
      is_execute: false
      method: "vader" # Options: "vader", "textblob", 
      file_input: "app/data/cleaned/tripadvisor_sentence_cleaned.csv"
      file_output: "app/data/cleaned/tripadvisor_sentences_labeled.csv"
    
    - type: eda
      is_execute: false
      file_input: "app/data/cleaned/tripadvisor_sentences_labeled.csv"

    - type: feature_extraction
      is_execute: false
      method: "tfidf"  # Options: "tfidf", "word2vec", "glove", "bert"
      file_input: "app/data/cleaned/tripadvisor_sentences_labeled.csv"
      feature_output: "app/data/features/tfidf_features.pkl"
      vector_output: "app/data/features/tfidf_vectorizer.pkl"
      ngram_min: 1
      ngram_max: 3

    - type: train_model
      is_execute: false
      method: "logistic_regression"
      file_input: "app/data/cleaned/tripadvisor_sentences_labeled.csv"
      feature_input: "app/data/features/tfidf_features.pkl"
      model_output: "app/data/train_models/tfidf_logistic_regression_sentiment_model.pkl"

    - type: predict_sentiment
      is_execute: true
      method: "logistic_regression"  # Options: "logistic_regression", "svm", "random_forest"
      file_input: "app/data/tests/test_reviews.csv"
      model_input: "app/data/train_models/tfidf_logistic_regression_sentiment_model.pkl"
      vector_input: "app/data/features/tfidf_vectorizer.pkl"
      file_output: "app/data/predictions/logistic_regression.csv"