services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nlp-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nlp-net

  app:
    image: ${APP_IMAGE}
    container_name: nlp-app
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - nlp-net

volumes:
  pgdata:
  pgadmin_data:

networks:
  nlp-net:
