# ---------------------
# Base image
# ---------------------
FROM python:3.11-slim


WORKDIR /app

RUN apt-get update && apt-get install -y build-essential wget curl && apt-get clean

# ---------------------
# Dev dependencies
# ---------------------
COPY requirements.txt requirements.txt
COPY requirements-dev.txt requirements-dev.txt

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements-dev.txt

# Download NLTK data
RUN python -m nltk.downloader vader_lexicon stopwords wordnet averaged_perceptron_tagger averaged_perceptron_tagger_eng

# (Optional) Preload model for dev testing
RUN python -c "from transformers import pipeline; pipeline('sentiment-analysis')"

# Copy full source code
COPY . .

ENV ENV=local

EXPOSE 8000

# Live reload for dev
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
