version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nlp-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nlp-net

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nlp-app-dev
    restart: unless-stopped
    env_file:
      - .env.development
    volumes:
      - .:/app  # Mount your local code for live editing
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - nlp-net
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8000/readiness"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10

volumes:
  pgdata:
  pgadmin_data:

networks:
  nlp-net:
