version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: nlp-postgres
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nlp-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - nlp-net

  app:
    build: .
    container_name: nlp-app
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - nlp-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  pgdata:
  pgadmin_data:

networks:
  nlp-net:
