apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-app
  labels:
    app: nlp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nlp-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0           # never create an extra pod
      maxUnavailable: 1     # ok to take the single pod down during update
  template:
    metadata:
      labels:
        app: nlp-app
    spec:
      terminationGracePeriodSeconds: 900  # 15 minutes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nlp-app
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nlp-app
          image: sokritha7/think-nlp-app:latest
          ports:
            - containerPort: 8000
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "30"]  # Delay shutdown for cleanup
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: "5432"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AWS_REGION
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AWS_S3_BUCKET_NAME
            - name: MAX_SIZE_FILE_UPLOAD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: MAX_SIZE_FILE_UPLOAD
            - name: BETTERSTACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: BETTERSTACK_API_KEY
            - name: BETTERSTACK_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: BETTERSTACK_HOST
            - name: OTEL_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: OTEL_SERVICE_NAME
            - name: OTEL_SERVICE_VERSION
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: OTEL_SERVICE_VERSION
            - name: OTEL_SAMPLE_RATIO
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: OTEL_SAMPLE_RATIO
            - name: OTEL_ENABLE_METRICS
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: OTEL_ENABLE_METRICS
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ENV
            - name: FRONTEND_ORIGIN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: FRONTEND_ORIGIN
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

