# k8s/cluster-issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-thinknlp-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sokritha.dev@gmail.com        # use your real email
    privateKeySecretRef:
      name: letsencrypt-thinknlp-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
