apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: alembic
          image: your-dockerhub-user/think-nlp-app:latest
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: supabase-secret
            - secretRef:
                name: app-secret
