apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: <IMAGE_PLACEHOLDER>
          command: ["alembic", "upgrade", "head"]
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: "5432"
            - name: ENV
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ENV