"""add file_hash to file_records

Revision ID: 0198edb78776
Revises: 887cea3cd152
Create Date: 2025-04-17 10:58:11.940651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0198edb78776'
down_revision: Union[str, None] = '887cea3cd152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('file_hash', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'file_records', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_records', type_='unique')
    op.drop_column('file_records', 'file_hash')
    # ### end Alembic commands ###
