"""add tokenized_config to file_record table

Revision ID: 0322a8ef3761
Revises: 677059eb043e
Create Date: 2025-08-19 06:49:21.067788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0322a8ef3761'
down_revision: Union[str, None] = '677059eb043e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('tokenized_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'tokenized_config')
    # ### end Alembic commands ###
