"""add special_cleaned_updated_at & tokenized_updated_at to file_records

Revision ID: 073a3406ba40
Revises: ad1d82976418
Create Date: 2025-04-22 13:57:07.735793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '073a3406ba40'
down_revision: Union[str, None] = 'ad1d82976418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('special_cleaned_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_records', sa.Column('tokenized_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'tokenized_updated_at')
    op.drop_column('file_records', 'special_cleaned_updated_at')
    # ### end Alembic commands ###
