"""add tokenized_hash to file_records

Revision ID: 12f788948bd3
Revises: 38b72596c6a3
Create Date: 2025-04-22 11:30:29.945031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f788948bd3'
down_revision: Union[str, None] = '38b72596c6a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('tokenized_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'tokenized_hash')
    # ### end Alembic commands ###
