"""add stopword config and updated_at

Revision ID: 29466d9b7b8d
Revises: 073a3406ba40
Create Date: 2025-04-22 14:23:46.228504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29466d9b7b8d'
down_revision: Union[str, None] = '073a3406ba40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('stopword_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_records', sa.Column('stopword_config', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'stopword_config')
    op.drop_column('file_records', 'stopword_updated_at')
    # ### end Alembic commands ###
