"""add stopword_s3_key and stopword_s3_url to file_record

Revision ID: 301a4bfc3539
Revises: a34d9fef142e
Create Date: 2025-04-18 19:26:07.146942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '301a4bfc3539'
down_revision: Union[str, None] = 'a34d9fef142e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('stopword_s3_key', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('stopword_s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'stopword_s3_url')
    op.drop_column('file_records', 'stopword_s3_key')
    # ### end Alembic commands ###
