"""add special_cleaned_flags  to file_records

Revision ID: 38b72596c6a3
Revises: a52a237bd845
Create Date: 2025-04-22 11:01:23.581630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38b72596c6a3'
down_revision: Union[str, None] = 'a52a237bd845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('special_cleaned_flags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'special_cleaned_flags')
    # ### end Alembic commands ###
