"""add lemmatized_updated_at in file_records

Revision ID: 41a446193e52
Revises: bf370e5e1974
Create Date: 2025-04-21 11:35:21.101204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a446193e52'
down_revision: Union[str, None] = 'bf370e5e1974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('lemmatized_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_topic_model_id'), 'topic_model', ['id'], unique=False)
    op.drop_constraint('topic_model_file_id_fkey', 'topic_model', type_='foreignkey')
    op.create_foreign_key(None, 'topic_model', 'file_records', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_model', type_='foreignkey')
    op.create_foreign_key('topic_model_file_id_fkey', 'topic_model', 'file_records', ['file_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_topic_model_id'), table_name='topic_model')
    op.drop_column('file_records', 'lemmatized_updated_at')
    # ### end Alembic commands ###
