"""create new table sentiment_analysis

Revision ID: 4d5a2afcc7c1
Revises: 5c89b6b516a9
Create Date: 2025-04-23 12:43:39.488954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5a2afcc7c1'
down_revision: Union[str, None] = '5c89b6b516a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentiment_analysis',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('topic_model_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('s3_url', sa.String(), nullable=True),
    sa.Column('overall_positive', sa.Float(), nullable=False),
    sa.Column('overall_neutral', sa.Float(), nullable=False),
    sa.Column('overall_negative', sa.Float(), nullable=False),
    sa.Column('per_topic_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['topic_model_id'], ['topic_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_analysis_id'), 'sentiment_analysis', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analysis_id'), table_name='sentiment_analysis')
    op.drop_table('sentiment_analysis')
    # ### end Alembic commands ###
