"""remove updated_at & add topic_updated_at, label_updated_at in topic_model

Revision ID: 50a8bb189d74
Revises: 55035cbd827b
Create Date: 2025-05-15 03:54:22.848086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a8bb189d74'
down_revision: Union[str, None] = '55035cbd827b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_model', sa.Column('topic_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('topic_model', sa.Column('label_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('topic_model', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_model', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('topic_model', 'label_updated_at')
    op.drop_column('topic_model', 'topic_updated_at')
    # ### end Alembic commands ###
