"""add eda_analysis and remove all the url of eda in file_record

Revision ID: 55035cbd827b
Revises: 7455935a52bf
Create Date: 2025-05-14 16:05:09.440153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55035cbd827b'
down_revision: Union[str, None] = '7455935a52bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('eda_analysis', sa.JSON(), nullable=True))
    op.drop_column('file_records', 'eda_text_length_url')
    op.drop_column('file_records', 'eda_trigram_url')
    op.drop_column('file_records', 'eda_bigram_url')
    op.drop_column('file_records', 'eda_wordcloud_url')
    op.drop_column('file_records', 'eda_word_freq_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('eda_word_freq_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_records', sa.Column('eda_wordcloud_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_records', sa.Column('eda_bigram_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_records', sa.Column('eda_trigram_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_records', sa.Column('eda_text_length_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('file_records', 'eda_analysis')
    # ### end Alembic commands ###
