"""add label_keywords and label_map_json in file_record

Revision ID: 5c89b6b516a9
Revises: 78ad522a4ada
Create Date: 2025-04-23 10:37:19.758581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c89b6b516a9'
down_revision: Union[str, None] = '78ad522a4ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_model', sa.Column('label_keywords', sa.String(), nullable=True))
    op.add_column('topic_model', sa.Column('label_map_json', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_model', 'label_map_json')
    op.drop_column('topic_model', 'label_keywords')
    # ### end Alembic commands ###
