"""add special_cleaned_s3_key and special_cleaned_s3_url to file_record

Revision ID: 6be981d55895
Revises: a351872d0bba
Create Date: 2025-04-18 15:00:26.682535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be981d55895'
down_revision: Union[str, None] = 'a351872d0bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('special_cleaned_s3_key', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('special_cleaned_s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'special_cleaned_s3_url')
    op.drop_column('file_records', 'special_cleaned_s3_key')
    # ### end Alembic commands ###
