"""remove s3_key and s3_url from sentiment_analysis

Revision ID: 6efc7910ed1d
Revises: 4d5a2afcc7c1
Create Date: 2025-04-23 13:04:50.679928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6efc7910ed1d'
down_revision: Union[str, None] = '4d5a2afcc7c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_analysis', 's3_url')
    op.drop_column('sentiment_analysis', 's3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sentiment_analysis', sa.Column('s3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
