"""add is_sample in file_record

Revision ID: 7455935a52bf
Revises: b746374a6181
Create Date: 2025-05-14 09:05:17.444376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7455935a52bf'
down_revision: Union[str, None] = 'b746374a6181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('is_sample', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'is_sample')
    # ### end Alembic commands ###
