"""add eda_updated_at in file_record

Revision ID: 78ad522a4ada
Revises: 29466d9b7b8d
Create Date: 2025-04-23 10:00:30.280352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78ad522a4ada'
down_revision: Union[str, None] = '29466d9b7b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('eda_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'eda_updated_at')
    # ### end Alembic commands ###
