"""add updated_at to sentiment_analysis

Revision ID: 7e585fff9c49
Revises: 6efc7910ed1d
Create Date: 2025-04-23 13:36:27.483696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e585fff9c49'
down_revision: Union[str, None] = '6efc7910ed1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_analysis', 'updated_at')
    # ### end Alembic commands ###
