"""add file_records table

Revision ID: 887cea3cd152
Revises: 317341a0e7d6
Create Date: 2025-04-15 20:08:12.382604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '887cea3cd152'
down_revision: Union[str, None] = '317341a0e7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('id', sa.String(), nullable=False))
    op.add_column('file_records', sa.Column('file_name', sa.String(), nullable=False))
    op.add_column('file_records', sa.Column('s3_url', sa.String(), nullable=False))
    op.add_column('file_records', sa.Column('columns', sa.String(), nullable=False))
    op.add_column('file_records', sa.Column('record_count', sa.Integer(), nullable=False))
    op.add_column('file_records', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_file_records_file_id', table_name='file_records')
    op.create_index(op.f('ix_file_records_id'), 'file_records', ['id'], unique=False)
    op.create_unique_constraint(None, 'file_records', ['s3_key'])
    op.drop_column('file_records', 'file_id')
    op.drop_column('file_records', 'stage')
    op.drop_column('file_records', 'file_url')
    op.drop_column('file_records', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('file_records', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('file_records', sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_records', sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file_records', type_='unique')
    op.drop_index(op.f('ix_file_records_id'), table_name='file_records')
    op.create_index('ix_file_records_file_id', 'file_records', ['file_id'], unique=False)
    op.drop_column('file_records', 'uploaded_at')
    op.drop_column('file_records', 'record_count')
    op.drop_column('file_records', 'columns')
    op.drop_column('file_records', 's3_url')
    op.drop_column('file_records', 'file_name')
    op.drop_column('file_records', 'id')
    # ### end Alembic commands ###
