"""Add ON DELET CASCADE to FKs

Revision ID: 93de1270632f
Revises: 50a8bb189d74
Create Date: 2025-05-30 03:28:23.417806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93de1270632f'
down_revision: Union[str, None] = '50a8bb189d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sentiment_analysis_topic_model_id_fkey', 'sentiment_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'sentiment_analysis', 'topic_model', ['topic_model_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('topic_model_file_id_fkey', 'topic_model', type_='foreignkey')
    op.create_foreign_key(None, 'topic_model', 'file_records', ['file_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic_model', type_='foreignkey')
    op.create_foreign_key('topic_model_file_id_fkey', 'topic_model', 'file_records', ['file_id'], ['id'])
    op.drop_constraint(None, 'sentiment_analysis', type_='foreignkey')
    op.create_foreign_key('sentiment_analysis_topic_model_id_fkey', 'sentiment_analysis', 'topic_model', ['topic_model_id'], ['id'])
    # ### end Alembic commands ###
