"""add tokenized_s3_key and tokenized_s3_url to file_record

Revision ID: a34d9fef142e
Revises: 6be981d55895
Create Date: 2025-04-18 18:00:52.432780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a34d9fef142e'
down_revision: Union[str, None] = '6be981d55895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('tokenized_s3_key', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('tokenized_s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'tokenized_s3_url')
    op.drop_column('file_records', 'tokenized_s3_key')
    # ### end Alembic commands ###
