"""add normalized_s3 columns to file_records

Revision ID: a351872d0bba
Revises: ee2ca75d3500
Create Date: 2025-04-17 16:30:25.440809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a351872d0bba'
down_revision: Union[str, None] = 'ee2ca75d3500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('normalized_s3_key', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('normalized_s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'normalized_s3_url')
    op.drop_column('file_records', 'normalized_s3_key')
    # ### end Alembic commands ###
