"""add normalized_broken_map to file_records

Revision ID: a52a237bd845
Revises: 41a446193e52
Create Date: 2025-04-22 10:45:02.775396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52a237bd845'
down_revision: Union[str, None] = '41a446193e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('normalized_broken_map', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'normalized_broken_map')
    # ### end Alembic commands ###
