"""remove tokenized_hash to file_records

Revision ID: ad1d82976418
Revises: 12f788948bd3
Create Date: 2025-04-22 13:43:23.662300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1d82976418'
down_revision: Union[str, None] = '12f788948bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'tokenized_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('tokenized_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
