"""ADD status field in sentiment_analysis table

Revision ID: b19789ca9917
Revises: 93de1270632f
Create Date: 2025-06-03 02:42:46.612324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19789ca9917'
down_revision: Union[str, None] = '93de1270632f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment_analysis', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiment_analysis', 'status')
    # ### end Alembic commands ###
