"""add EDA image urls to file_records

Revision ID: b91894222215
Revises: dab31d45cc69
Create Date: 2025-04-20 11:18:27.373646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91894222215'
down_revision: Union[str, None] = 'dab31d45cc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('eda_wordcloud_url', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('eda_text_length_url', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('eda_word_freq_url', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('eda_bigram_url', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('eda_trigram_url', sa.String(), nullable=True))
    op.drop_column('file_records', 'lemmatized_s3_url')
    op.drop_column('file_records', 'lemmatized_s3_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('lemmatized_s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file_records', sa.Column('lemmatized_s3_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('file_records', 'eda_trigram_url')
    op.drop_column('file_records', 'eda_bigram_url')
    op.drop_column('file_records', 'eda_word_freq_url')
    op.drop_column('file_records', 'eda_text_length_url')
    op.drop_column('file_records', 'eda_wordcloud_url')
    # ### end Alembic commands ###
