"""add special_cleaned_removed to file_record

Revision ID: bb20078e38d7
Revises: 248cfb3e61e0
Create Date: 2025-05-03 06:18:10.979203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb20078e38d7'
down_revision: Union[str, None] = '248cfb3e61e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('special_cleaned_removed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'special_cleaned_removed')
    # ### end Alembic commands ###
