"""add table topic_modeling

Revision ID: bf370e5e1974
Revises: 6c0482e088d1
Create Date: 2025-04-20 22:02:08.689788

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf370e5e1974"
down_revision: Union[str, None] = "6c0482e088d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        "topic_model",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("topic_count", sa.Integer(), nullable=True),
        sa.Column("s3_key", sa.String(), nullable=False, unique=True),
        sa.Column("s3_url", sa.String(), nullable=False),
        sa.Column("summary_json", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["file_id"], ["file_records.id"], ondelete="CASCADE"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_topic_model_id"), table_name="topic_model")
    op.drop_table("topic_model")
    # ### end Alembic commands ###
