"""add lemmatized_s3 fields to file_records

Revision ID: bfa1c559324a
Revises: b91894222215
Create Date: 2025-04-20 11:22:59.550858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa1c559324a'
down_revision: Union[str, None] = 'b91894222215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('lemmatized_s3_key', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('lemmatized_s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'lemmatized_s3_url')
    op.drop_column('file_records', 'lemmatized_s3_key')
    # ### end Alembic commands ###
