"""add lemmatized_s3_key and lemmatizaed_s3_url to file_record

Revision ID: dab31d45cc69
Revises: 301a4bfc3539
Create Date: 2025-04-19 09:38:56.541995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab31d45cc69'
down_revision: Union[str, None] = '301a4bfc3539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('lemmatized_s3_key', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('lemmatized_s3_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_records', 'lemmatized_s3_url')
    op.drop_column('file_records', 'lemmatized_s3_key')
    # ### end Alembic commands ###
