apiVersion: 1

datasources:
  - name: Prometheus
    uid: prom
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      # Map Prometheus exemplars → Jaeger traces (trace_id label)
      exemplarTraceIdDestinations:
        - name: Jaeger
          datasourceUid: jaeger
          traceIdLabelName: trace_id

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: prom
